### ISSUE TITLE
hardcode admissible ranges for each ephys property

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_org#99] opened 2015-08-21 15:33 UTC
When showing ephys data in graph views, we should hard code an acceptable range and not show data that falls outside of range (i.e., positive Vrest, negative Rin, etc)

**Comment by dtebaykin** [comment] 2015-09-11 00:12
Duplicate of issue#20

**Closed** 2015-09-11 00:13 UTC
