### ISSUE TITLE
Spike amplitude normalized values don't get saved (because of EPSP/C override)

### ISSUE THREAD

**Issue by rgerkin** [neuroelectro/neuroelectro_org#7] opened 2014-09-07 07:44 UTC
1. why do some spike amplitude values have no normalized values - because of earlier psp / psc error checking - in function normalize_nedm_val in compute_field_summaries.py
2. merge ephys properties spike peak and spike overshoot - these are actually the same property

---------------------------------------
- Bitbucket: https://bitbucket.org/rgerkin/neuroelectro_org/issue/7
- Originally Reported By: [Shreejoy Tripathy](http://bitbucket.org/shreejoy)
- Originally Created At: 2014-06-24T01:31:59.277

**Comment by stripathy** [comment] 2015-09-08 04:41
deleting since essentially duplicate of #97

**Closed** 2015-09-08 04:41 UTC
